[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    api: API tests
    ui: UI tests
filterwarnings =
    ignore::urllib3.exceptions.NotOpenSSLWarning
    ignore::urllib3.exceptions.InsecureRequestWarning
    ignore::DeprecationWarning
    ignore
addopts = -p no:warnings